name: Workflow for Codecov example-python

on:
  push:
  pull_request:

jobs:
  upload_coverage:
    runs-on: ubuntu-latest  # Replace with your preferred runner
    steps:
      - uses: actions/checkout@v4  # Checkout your code repository
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: smart-tests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
