name: Workflow for Codecov example-python

on:
  push:
  pull_request:

jobs:
  upload_coverage:
    runs-on: ubuntu-latest  # Replace with your preferred runner
    steps:
      - uses: actions/checkout@v4  # Checkout your code repository
      - name: Install codecov
        run: |
          curl -fsSL https://codecov.io/bash | bash  # Install the Codecov CLI
      - name: Upload coverage report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}  # Replace with your secret name
        run: codecov -t $CODECOV_TOKEN -f ./coverage.xml  # Replace with your report path

