name: Workflow for Codecov example-python

on:
  push:
  pull_request:

jobs:
  upload_coverage:
    runs-on: ubuntu-latest  # Replace with your preferred runner
    steps:
    - uses: actions/checkout@main
    - uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true # optional (default = false)
        files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        token: 60d09c03-55dd-443f-984a-0bed2c7df9d2
        verbose: true # optional (default = false)
