name: Workflow for Codecov example-python

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      
      - name: Install dependencies
        run: |
          pipenv install 
      
      - name: Run ATS
        uses: codecov/codecov-ats@v0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Run tests and collect coverage
        run: |
          pipenv run pytest --cov app ${{ env.CODECOV_ATS_TESTS }}
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: smart-tests
          verbose: true
